# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iskratel', '0003_auto_20160908_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'ordering': ['id'], 'verbose_name': 'Разделы', 'verbose_name_plural': 'Верхнее меню TAB - разделы закладок'},
        ),
        migrations.AlterModelOptions(
            name='bookmarksubmenu',
            options={'ordering': ['nametabsubmenu'], 'verbose_name': 'Топики подменю', 'verbose_name_plural': 'Подменю'},
        ),
    ]
