# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iskratel', '0004_auto_20160909_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'ordering': ['id'], 'verbose_name': 'Название Раздела', 'verbose_name_plural': 'Верхнее меню TAB - разделы закладок'},
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='nametab',
            field=models.CharField(max_length=30, unique=True, verbose_name='Раздел TAB'),
        ),
        migrations.AlterField(
            model_name='bookmarksubmenu',
            name='namesub',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название подменю'),
        ),
        migrations.AlterField(
            model_name='bookmarksubmenu',
            name='nametabsubmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iskratel.bookmarks', verbose_name='Раздел:'),
        ),
    ]
