# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iskratel', '0005_auto_20160916_0902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmarksubmenu',
            unique_together=set([('namesub', 'nametabsubmenu')]),
        ),
    ]
